### ISSUE TITLE
API Deprecation

### ISSUE THREAD

**Issue by UrsaLongsight** [Mythos-Softworks/Arbeiterbiene#15]
As of October 16, 2017 [all APIs prior to v6 will be deprecated](https://discordapp.com/developers/docs/reference#api-versioning). Arbeiterbiene needs to be compliant by that date to ensure there isn't an interruption of service. Unless an API is being specified currently, Arbeiterbiene is using the current default of v3.

**Comment by UrsaLongsight** [comment]
[Here](https://discordapp.com/developers/docs/change-log) is a list of changes for v6. This is probably from v5, so there are probably more between the version Arbeiterbiene is using and v6.

**Comment by jayspur11** [comment]
Looks like `discord.py` was actually using the proper API version, so no update was needed.
